spring:
  profiles: local

logging:
  config: classpath:log/log4j2-local.xml
---
spring:
  profiles: dev


logging:
  config: classpath:log/log4j2-test.xml

---
spring:
  profiles: real

logging:
  config: classpath:log/log4j2-release.xml