spring:
  profiles:
    active: local
    include: swagger, mongo, logging, key
  batch:
    job:
      enabled: false

server:
  port: 8083

management:
  endpoints.web.base-path: /application
  endpoints.web.exposure.include: '*'

---