spring:
  profiles:
    active: local
    include: mongo, logging, key
#  batch:
#    job:
#      enabled: false

server:
  port: 8081

management:
  endpoints.web.base-path: /application
  endpoints.web.exposure.include: '*'

---